// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlM1Ic4QybkGF7gykJvwBwBZ9lJy1CXac',
    appId: '1:127275104503:web:d554122094083478dfbbf2',
    messagingSenderId: '127275104503',
    projectId: 'summarization-8fc77',
    authDomain: 'summarization-8fc77.firebaseapp.com',
    storageBucket: 'summarization-8fc77.firebasestorage.app',
    measurementId: 'G-P6BTVG3B7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiq_Vj2UQe-IDx2tDrXO-9HjMaXx_t1A',
    appId: '1:127275104503:android:d2e6359675f80784dfbbf2',
    messagingSenderId: '127275104503',
    projectId: 'summarization-8fc77',
    storageBucket: 'summarization-8fc77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJmM2pEGIFrjUGpTngRLWMMTkMzXLzqyw',
    appId: '1:127275104503:ios:312f66d46e492d65dfbbf2',
    messagingSenderId: '127275104503',
    projectId: 'summarization-8fc77',
    storageBucket: 'summarization-8fc77.firebasestorage.app',
    iosBundleId: 'com.example.aiVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJmM2pEGIFrjUGpTngRLWMMTkMzXLzqyw',
    appId: '1:127275104503:ios:312f66d46e492d65dfbbf2',
    messagingSenderId: '127275104503',
    projectId: 'summarization-8fc77',
    storageBucket: 'summarization-8fc77.firebasestorage.app',
    iosBundleId: 'com.example.aiVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlM1Ic4QybkGF7gykJvwBwBZ9lJy1CXac',
    appId: '1:127275104503:web:c682fb5f41850d0adfbbf2',
    messagingSenderId: '127275104503',
    projectId: 'summarization-8fc77',
    authDomain: 'summarization-8fc77.firebaseapp.com',
    storageBucket: 'summarization-8fc77.firebasestorage.app',
    measurementId: 'G-VEQBPESBGM',
  );
}